# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class DocumentInfoFieldEntryRect(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, x: float=None, y: float=None, w: float=None, h: float=None):  # noqa: E501
        """DocumentInfoFieldEntryRect - a model defined in Swagger

        :param x: The x of this DocumentInfoFieldEntryRect.  # noqa: E501
        :type x: float
        :param y: The y of this DocumentInfoFieldEntryRect.  # noqa: E501
        :type y: float
        :param w: The w of this DocumentInfoFieldEntryRect.  # noqa: E501
        :type w: float
        :param h: The h of this DocumentInfoFieldEntryRect.  # noqa: E501
        :type h: float
        """
        self.swagger_types = {
            'x': float,
            'y': float,
            'w': float,
            'h': float
        }

        self.attribute_map = {
            'x': 'x',
            'y': 'y',
            'w': 'w',
            'h': 'h'
        }

        self._x = x
        self._y = y
        self._w = w
        self._h = h

    @classmethod
    def from_dict(cls, dikt) -> 'DocumentInfoFieldEntryRect':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DocumentInfoFieldEntry_rect of this DocumentInfoFieldEntryRect.  # noqa: E501
        :rtype: DocumentInfoFieldEntryRect
        """
        return util.deserialize_model(dikt, cls)

    @property
    def x(self) -> float:
        """Gets the x of this DocumentInfoFieldEntryRect.


        :return: The x of this DocumentInfoFieldEntryRect.
        :rtype: float
        """
        return self._x

    @x.setter
    def x(self, x: float):
        """Sets the x of this DocumentInfoFieldEntryRect.


        :param x: The x of this DocumentInfoFieldEntryRect.
        :type x: float
        """
        if x is None:
            raise ValueError("Invalid value for `x`, must not be `None`")  # noqa: E501

        self._x = x

    @property
    def y(self) -> float:
        """Gets the y of this DocumentInfoFieldEntryRect.


        :return: The y of this DocumentInfoFieldEntryRect.
        :rtype: float
        """
        return self._y

    @y.setter
    def y(self, y: float):
        """Sets the y of this DocumentInfoFieldEntryRect.


        :param y: The y of this DocumentInfoFieldEntryRect.
        :type y: float
        """
        if y is None:
            raise ValueError("Invalid value for `y`, must not be `None`")  # noqa: E501

        self._y = y

    @property
    def w(self) -> float:
        """Gets the w of this DocumentInfoFieldEntryRect.


        :return: The w of this DocumentInfoFieldEntryRect.
        :rtype: float
        """
        return self._w

    @w.setter
    def w(self, w: float):
        """Sets the w of this DocumentInfoFieldEntryRect.


        :param w: The w of this DocumentInfoFieldEntryRect.
        :type w: float
        """
        if w is None:
            raise ValueError("Invalid value for `w`, must not be `None`")  # noqa: E501

        self._w = w

    @property
    def h(self) -> float:
        """Gets the h of this DocumentInfoFieldEntryRect.


        :return: The h of this DocumentInfoFieldEntryRect.
        :rtype: float
        """
        return self._h

    @h.setter
    def h(self, h: float):
        """Sets the h of this DocumentInfoFieldEntryRect.


        :param h: The h of this DocumentInfoFieldEntryRect.
        :type h: float
        """
        if h is None:
            raise ValueError("Invalid value for `h`, must not be `None`")  # noqa: E501

        self._h = h
