# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class DocumentID(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, title: str=None):  # noqa: E501
        """DocumentID - a model defined in Swagger

        :param id: The id of this DocumentID.  # noqa: E501
        :type id: str
        :param title: The title of this DocumentID.  # noqa: E501
        :type title: str
        """
        self.swagger_types = {
            'id': str,
            'title': str
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title'
        }

        self._id = id
        self._title = title

    @classmethod
    def from_dict(cls, dikt) -> 'DocumentID':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DocumentID of this DocumentID.  # noqa: E501
        :rtype: DocumentID
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this DocumentID.

        The document ID  # noqa: E501

        :return: The id of this DocumentID.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this DocumentID.

        The document ID  # noqa: E501

        :param id: The id of this DocumentID.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def title(self) -> str:
        """Gets the title of this DocumentID.

        The document title  # noqa: E501

        :return: The title of this DocumentID.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this DocumentID.

        The document title  # noqa: E501

        :param title: The title of this DocumentID.
        :type title: str
        """

        self._title = title
